# Generated by Django 3.2 on 2021-04-17 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
